import { MigrationInterface, QueryRunner } from 'typeorm';


const whiteCardTextList = [
    'Coat hanger abortions.',
    'Man meat.',
    'Autocannibalism.',
    'Vigorous jazz hands.',
    'Flightless birds.',
    'Pictures of boobs.',
    'Doing the right thing.',
    'Hunting accidents.',
    'A cartoon camel enjoying the smooth, refreshing taste of a cigarette.',
    'The violation of our most basic human rights.',
    'Viagra®.',
    'Self-loathing.',
    'Spectacular abs.',
    'An honest cop with nothing left to lose.',
    'Abstinence.',
    'A balanced breakfast.',
    'Mountain Dew Code Red.',
    'Concealing a boner.',
    'Roofies.',
    'Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.',
    'Tweeting.',
    'The Big Bang.',
    'Amputees.',
    'The Rev. Dr. Martin Luther King, Jr.',
    'Former President George W. Bush.',
    'Being marginalized.',
    'Smegma.',
    'Laying an egg.',
    'Cuddling.',
    'Aaron Burr.',
    'The Pope.',
    'A bleached asshole.',
    'Horse meat.',
    'Genital piercings.',
    'Fingering.',
    'Elderly Japanese men.',
    'Stranger danger.',
    'Fear itself.',
    'Science.',
    'Praying the gay away.',
    'Same-sex ice dancing.',
    'The terrorists.',
    'Making sex at her.',
    'German dungeon porn.',
    'Bingeing and purging.',
    'Ethnic cleansing.',
    'Cheating in the Special Olympics.',
    'Nickelback.',
    'Heteronormativity.',
    'William Shatner.',
    'Making a pouty face.',
    'Chainsaws for hands.',
    'The placenta.',
    'The profoundly handicapped.',
    'Tom Cruise.',
    'Object permanence.',
    'Goblins.',
    'An icepick lobotomy.',
    'Arnold Schwarzenegger.',
    'Hormone injections.',
    'A falcon with a cap on its head.',
    'Foreskin.',
    'Dying.',
    'Stunt doubles.',
    'The invisible hand.',
    'Jew-fros.',
    'A really cool hat.',
    'Flash flooding.',
    'Flavored condoms.',
    'Dying of dysentery.',
    'Sexy pillow fights.',
    'The Three-Fifths compromise.',
    'A sad handjob.',
    'Men.',
    'Historically black colleges.',
    'Sean Penn.',
    'Heartwarming orphans.',
    'Waterboarding.',
    'The clitoris.',
    'Vikings.',
    'Friends who eat all the snacks.',
    'The Underground Railroad.',
    'Pretending to care.',
    'Raptor attacks.',
    'A micropenis.',
    'A Gypsy curse.',
    'Agriculture.',
    'Bling.',
    'A clandestine butt scratch.',
    'The South.',
    'Sniffing glue.',
    'Consultants.',
    'My humps.',
    'Geese.',
    'Being a dick to children.',
    'Party poopers.',
    'Sunshine and rainbows.',
    'YOU MUST CONSTRUCT ADDITIONAL PYLONS.',
    'Mutually-assured destruction.',
    'Heath Ledger.',
    'Sexting.',
    'An Oedipus complex.',
    'Eating all of the cookies before the AIDS bake-sale.',
    'A sausage festival.',
    'Michael Jackson.',
    'Skeletor.',
    'Chivalry.',
    'Sharing needles.',
    'Being rich.',
    'Muzzy.',
    'Count Chocula.',
    'Spontaneous human combustion.',
    'College.',
    'Necrophilia.',
    'The Chinese gymnastics team.',
    'Global warming.',
    'Farting and walking away.',
    'Emotions.',
    'Uppercuts.',
    'Cookie Monster devouring the Eucharist wafers.',
    'Stifling a giggle at the mention of Hutus and Tutsis.',
    'Penis envy.',
    'Letting yourself go.',
    'White people.',
    'Dick Cheney.',
    'Leaving an awkward voicemail.',
    'Yeast.',
    'Natural selection.',
    'Masturbation.',
    'Twinkies®.',
    'A LAN party.',
    'Opposable thumbs.',
    'A grande sugar-free iced soy caramel macchiato.',
    'Soiling oneself.',
    'A sassy black woman.',
    'Sperm whales.',
    'Teaching a robot to love.',
    'Scrubbing under the folds.',
    'A drive-by shooting.',
    'Whipping it out.',
    'Panda sex.',
    'Catapults.',
    'Will Smith.',
    'Toni Morrison\'s vagina.',
    'Five-Dollar Footlongs™.',
    'Land mines.',
    'A sea of troubles.',
    'A zesty breakfast burrito.',
    'Christopher Walken.',
    'Friction.',
    'Balls.',
    'AIDS.',
    'The KKK.',
    'Figgy pudding.',
    'Seppuku.',
    'Marky Mark and the Funky Bunch.',
    'Gandhi.',
    'Dave Matthews Band.',
    'Preteens.',
    'The token minority.',
    'Friends with benefits.',
    'Re-gifting.',
    'Pixelated bukkake.',
    'Substitute teachers.',
    'Take-backsies.',
    'A thermonuclear detonation.',
    'The Tempur-Pedic® Swedish Sleep System™.',
    'Waiting \'til marriage.',
    'A tiny horse.',
    'A can of whoop-ass.',
    'Dental dams.',
    'Feeding Rosie O\'Donnell.',
    'Old-people smell.',
    'Genghis Khan.',
    'Authentic Mexican cuisine.',
    'Oversized lollipops.',
    'Garth Brooks.',
    'Keanu Reeves.',
    'Drinking alone.',
    'The American Dream.',
    'Taking off your shirt.',
    'Giving 110%.',
    'Flesh-eating bacteria.',
    'Child abuse.',
    'A cooler full of organs.',
    'A moment of silence.',
    'The Rapture.',
    'Keeping Christ in Christmas.',
    'RoboCop.',
    'That one gay Teletubby.',
    'Sweet, sweet vengeance.',
    'Fancy Feast®.',
    'Pooping back and forth. Forever.',
    'Being a motherfucking sorcerer.',
    'Jewish fraternities.',
    'Edible underpants.',
    'Poor people.',
    'All-you-can-eat shrimp for $4.99.',
    'Britney Spears at 55.',
    'That thing that electrocutes your abs.',
    'The folly of man.',
    'Fiery poops.',
    'Cards Against Humanity.',
    'A murder most foul.',
    'Me time.',
    'The inevitable heat death of the universe.',
    'Nocturnal emissions.',
    'Daddy issues.',
    'The hardworking Mexican.',
    'Natalie Portman.',
    'Waking up half-naked in a Denny\'s parking lot.',
    'Nipple blades.',
    'Assless chaps.',
    'Full frontal nudity.',
    'Hulk Hogan.',
    'Passive-agression.',
    'Ronald Reagan.',
    'Vehicular manslaughter.',
    'Menstruation.',
    'Pulling out.',
    'Picking up girls at the abortion clinic.',
    'The homosexual agenda.',
    'The Holy Bible.',
    'World peace.',
    'Dropping a chandelier on your enemies and riding the rope up.',
    'Testicular torsion.',
    'The milk man.',
    'A time travel paradox.',
    'Hot Pockets®.',
    'Guys who don\'t call.',
    'Eating the last known bison.',
    'Darth Vader.',
    'Scalping.',
    'Homeless people.',
    'The World of Warcraft.',
    'Gloryholes.',
    'Saxophone solos.',
    'Sean Connery.',
    'God.',
    'Intelligent design.',
    'The taint; the grundle; the fleshy fun-bridge.',
    'Friendly fire.',
    'Keg stands.',
    'Eugenics.',
    'A good sniff.',
    'Lockjaw.',
    'A neglected Tamagotchi™.',
    'The People\'s Elbow.',
    'Robert Downey, Jr.',
    'The heart of a child.',
    'Seduction.',
    'Smallpox blankets.',
    'Licking things to claim them as your own.',
    'A salty surprise.',
    'Poorly-timed Holocaust jokes.',
    'My soul.',
    'My sex life.',
    'Pterodactyl eggs.',
    'Altar boys.',
    'Forgetting the Alamo.',
    '72 virgins.',
    'Raping and pillaging.',
    'Pedophiles.',
    'Eastern European Turbo-Folk music.',
    'A snapping turtle biting the tip of your penis.',
    'Pabst Blue Ribbon.',
    'Domino\'s™ Oreo™ Dessert Pizza.',
    'My collection of high-tech sex toys.',
    'A middle-aged man on roller skates.',
    'The Blood of Christ.',
    'Half-assed foreplay.',
    'Free samples.',
    'Douchebags on their iPhones.',
    'Hurricane Katrina.',
    'Wearing underwear inside-out to avoid doing laundry.',
    'Republicans.',
    'The glass ceiling.',
    'A foul mouth.',
    'Jerking off into a pool of children\'s tears.',
    'Getting really high.',
    'The deformed.',
    'Michelle Obama\'s arms.',
    'Explosions.',
    'The Übermensch.',
    'Donald Trump.',
    'Sarah Palin.',
    'Attitude.',
    'This answer is postmodern.',
    'Crumpets with the Queen.',
    'Frolicking.',
    'Team-building exercises.',
    'Repression.',
    'Road head.',
    'A bag of magic beans.',
    'An asymmetric boob job.',
    'Dead parents.',
    'Public ridicule.',
    'A mating display.',
    'A mime having a stroke.',
    'Stephen Hawking talking dirty.',
    'African children.',
    'Mouth herpes.',
    'Overcompensation.',
    'Bill Nye the Science Guy.',
    'Bitches.',
    'Italians.',
    'Have some more kugel.',
    'A windmill full of corpses.',
    'Her Royal Highness, Queen Elizabeth II.',
    'Crippling debt.',
    'Adderall™.',
    'A stray pube.',
    'Shorties and blunts.',
    'Passing a kidney stone.',
    'Prancing.',
    'Leprosy.',
    'A brain tumor.',
    'Bees?',
    'Puppies!',
    'Cockfights.',
    'Kim Jong-il.',
    'Hope.',
    '8 oz. of sweet Mexican black-tar heroin.',
    'Incest.',
    'Grave robbing.',
    'Asians who aren\'t good at math.',
    'Alcoholism.',
    '(I am doing Kegels right now.)',
    'Justin Bieber.',
    'The Jews.',
    'Bestiality.',
    'Winking at old people.',
    'Drum circles.',
    'Kids with ass cancer.',
    'Loose lips.',
    'Auschwitz.',
    'Civilian casualties.',
    'Inappropriate yelling.',
    'Tangled Slinkys.',
    'Being on fire.',
    'The Thong Song.',
    'A vajazzled vagina.',
    'Riding off into the sunset.',
    'Exchanging pleasantries.',
    'My relationship status.',
    'Shaquille O\'Neal\'s acting career.',
    'Being fabulous.',
    'Lactation.',
    'Not reciprocating oral sex.',
    'Sobbing into a Hungry-Man® Frozen Dinner.',
    'My genitals.',
    'Date rape.',
    'Ring Pops™.',
    'GoGurt®.',
    'Judge Judy.',
    'Lumberjack fantasies.',
    'The gays.',
    'Scientology.',
    'Estrogen.',
    'Police brutality.',
    'Passable transvestites.',
    'The Virginia Tech Massacre.',
    'Tiger Woods.',
    'Dick fingers.',
    'Racism.',
    'Glenn Beck being harried by a swarm of buzzards.',
    'Surprise sex!',
    'Classist undertones.',
    'Booby-trapping the house to foil burglars.',
    'New Age music.',
    'PCP.',
    'A lifetime of sadness.',
    'Doin\' it in the butt.',
    'Swooping.',
    'The Hamburglar.',
    'Tentacle porn.',
    'A hot mess.',
    'Too much hair gel.',
    'A look-see.',
    'Not giving a shit about the Third World.',
    'American Gladiators.',
    'The Kool-Aid Man.',
    'Mr. Snuffleupagus.',
    'Barack Obama.',
    'Golden showers.',
    'Wiping her butt.',
    'Queefing.',
    'Getting drunk on mouthwash.',
    'An M. Night Shyamalan plot twist.',
    'A robust mongoloid.',
    'Nazis.',
    'White privilege.',
    'An erection that lasts longer than four hours.',
    'A disappointing birthday party.',
    'Puberty.',
    'Two midgets shitting into a bucket.',
    'Wifely duties.',
    'The forbidden fruit.',
    'Getting so angry that you pop a boner.',
    'Sexual tension.',
    'Third base.',
    'A gassy antelope.',
    'Those times when you get sand in your vagina.',
    'A Super Soaker™ full of cat pee.',
    'Muhammed (Praise Be Unto Him).',
    'Racially-biased SAT questions.',
    'Porn stars.',
    'A fetus.',
    'Obesity.',
    'When you fart and a little bit comes out.',
    'Oompa-Loompas.',
    'BATMAN!!!',
    'Black people.',
    'Tasteful sideboob.',
    'Hot people.',
    'Grandma.',
    'Copping a feel.',
    'The Trail of Tears.',
    'Famine.',
    'Finger painting.',
    'The miracle of childbirth.',
    'Goats eating coins.',
    'A monkey smoking a cigar.',
    'Faith healing.',
    'Parting the Red Sea.',
    'Dead babies.',
    'The Amish.',
    'Impotence.',
    'Child beauty pageants.',
    'Centaurs.',
    'AXE Body Spray.',
    'Kanye West.',
    'Women\'s suffrage.',
    'Children on leashes.',
    'Harry Potter erotica.',
    'The Dance of the Sugar Plum Fairy.',
    'Lance Armstrong\'s missing testicle.',
    'Dwarf tossing.',
    'Mathletes.',
    'Lunchables™.',
    'Women in yogurt commercials.',
    'John Wilkes Booth.',
    'Powerful thighs.',
    'Mr. Clean, right behind you.',
    'Multiple stab wounds.',
    'Cybernetic enhancements.',
    'Serfdom.',
    'Another goddamn vampire movie.',
    'Glenn Beck catching his scrotum on a curtain hook.',
    'A big hoopla about nothing.',
    'Peeing a little bit.',
    'The Hustle.',
    'Ghosts.',
    'Bananas in Pajamas.',
    'Active listening.',
    'Dry heaving.',
    'Kamikaze pilots.',
    'The Force.',
    'Anal beads.',
    'The Make-A-Wish® Foundation.',
    'Flying sex snakes.',
    'MechaHitler.',
    'Getting naked and watching Nickelodeon.',
    'Charisma.',
    'Morgan Freeman\'s voice.',
    'Breaking out into song and dance.',
    'Soup that is too hot.',
    'Chutzpah.',
    'Unfathomable stupidity.',
    'Horrifying laser hair removal accidents.',
    'Boogers.',
    'A Bop It™.',
    'Expecting a burp and vomiting on the floor.',
    'A defective condom.',
    'Teenage pregnancy.',
    'Hot cheese.',
    'A mopey zoo lion.',
    'Shapeshifters.',
    'The Care Bear Stare.',
    'Erectile dysfunction.',
    'The chronic.',
    'Home video of Oprah sobbing into a Lean Cuisine®.',
    'Tweeting.',
    'Firing a rifle into the air while balls deep in a squealing hog.',
    'Nicolas Cage.',
    'Euphoria™ by Calvin Klein.',
    'Switching to Geico®.',
    'A gentle caress of the inner thigh.',
    'Poor life choices.',
    'Embryonic stem cells.',
    'Customer service representatives.',
    'The Little Engine That Could.',
    'Lady Gaga.',
    'A death ray.',
    'Vigilante justice.',
    'Exactly what you\'d expect.',
    'Natural male enhancement.',
    'Passive-aggressive Post-it notes.',
    'Inappropriate yodeling.',
    'A homoerotic volleyball montage.',
    'Actually taking candy from a baby.',
    'Jibber-jabber.',
    'Crystal meth.',
    'My inner demons.',
    'Pac-Man uncontrollably guzzling cum.',
    'My vagina.',
    'The Donald Trump Seal of Approval™.',
    'The true meaning of Christmas.',
    'testtest',
    'End Canadian White Cards',
    'end misprint bonus card',
    'A big black dick.',
    'A beached whale.',
    'A bloody pacifier.',
    'A crappy little hand.',
    'A low standard of living.',
    'A nuanced critique.',
    'Panty raids.',
    'A passionate Latino lover.',
    'A rival dojo.',
    'A web of lies.',
    'A woman scorned.',
    'Clams.',
    'Apologizing.',
    'Appreciative snapping.',
    'Neil Patrick Harris.',
    'Beating your wives.',
    'Being a dinosaur.',
    'Shaft.',
    'Bosnian chicken farmers.',
    'Nubile slave boys.',
    'Carnies.',
    'Coughing into a vagina.',
    'Suicidal thoughts.',
    'Dancing with a broom.',
    'Deflowering the princess.',
    'Dorito breath.',
    'Eating an albino.',
    'Enormous Scandinavian women.',
    'Fabricating statistics.',
    'Finding a skeleton.',
    'Gandalf.',
    'Genetically engineered super-soldiers.',
    'George Clooney\'s musk.',
    'Getting abducted by Peter Pan.',
    'Getting in her pants, politely.',
    'Gladiatorial combat.',
    'Good grammar.',
    'Hipsters.',
    'Historical revisionism.',
    'Insatiable bloodlust.',
    'Jafar.',
    'Jean-Claude Van Damme.',
    'Just the tip.',
    'Mad hacky-sack skills.',
    'Leveling up.',
    'Literally eating shit.',
    'Making the penises kiss.',
    'Media coverage.',
    'Medieval Times® Dinner & Tournament.',
    'Moral ambiguity.',
    'My machete.',
    'One thousand Slim Jims.',
    'Ominous background music.',
    'Overpowering your father.',
    'Pistol-whipping a hostage.',
    'Quiche.',
    'Quivering jowls.',
    'Revenge fucking.',
    'Ripping into a man\'s chest and pulling out his still-beating heart.',
    'Ryan Gosling riding in on a white horse.',
    'Santa Claus.',
    'Scrotum tickling.',
    'Sexual humiliation.',
    'Sexy Siamese twins.',
    'Slow motion.',
    'Space muffins.',
    'Statistically validated stereotypes.',
    'Sudden Poop Explosion Disease.',
    'The boners of the elderly.',
    'The economy.',
    'The Fanta® girls.',
    'The Gulags.',
    'The harsh light of day.',
    'The hiccups.',
    'The shambling corpse of Larry King.',
    'The four arms of Vishnu.',
    'Being a busy adult with many important things to do.',
    'Tripping balls.',
    'Words, words, words.',
    'Zeus\'s sexual appetites.',
    'end First Expansion',
    'A bigger, blacker dick.',
    'The mere concept of Applebee\'s®.',
    'A sad fat dragon with no friends.',
    'Catastrophic urethral trauma.',
    'Hillary Clinton\'s death stare.',
    'Existing.',
    'A piñata full of scorpions.',
    'Mooing.',
    'Swiftly achieving orgasm.',
    'Daddy\'s belt.',
    'Double penetration.',
    'Weapons-grade plutonium.',
    'Some really fucked-up shit.',
    'Subduing a grizzly bear and making her your wife.',
    'Rising from the grave.',
    'The mixing of the races.',
    'Taking a man\'s eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.',
    'Scrotal frostbite.',
    'All of this blood.',
    'Loki, the trickster god.',
    'Whining like a little bitch.',
    'Pumping out a baby every nine months.',
    'Tongue.',
    'Finding Waldo.',
    'Upgrading homeless people to mobile hotspots.',
    'Wearing an octopus for a hat.',
    'An unhinged ferris wheel rolling toward the sea.',
    'Living in a trashcan.',
    'The corporations.',
    'A magic hippie love butt.',
    'Fuck Mountain.',
    'Survivor\'s guilt.',
    'Me.',
    'Getting hilariously gang-banged by the Blue Man Group.',
    'Jeff Goldblum.',
    'Making a friend.',
    'A soulful rendition of "Ol\' Man River.',
    'Intimacy problems.',
    'A sweaty, panting leather daddy.',
    'Spring break!',
    'Being awesome at sex.',
    'Dining with cardboard cutouts of the cast of "Friends."',
    'Another shot of morphine.',
    'Beefin\' over turf.',
    'A squadron of moles wearing aviator goggles.',
    'Bullshit.',
    'The Google.',
    'Pretty Pretty Princess Dress-Up Board Game®.',
    'The new Radiohead album.',
    'An army of skeletons.',
    'A man in yoga pants with a ponytail and feather earrings.',
    'Mild autism.',
    'Nunchuck moves.',
    'Whipping a disobedient slave.',
    'An ether-soaked rag.',
    'A sweet spaceship.',
    'A 55-gallon drum of lube.',
    'Special musical guest, Cher.',
    'The human body.',
    'Boris the Soviet Love Hammer.',
    'The grey nutrient broth that sustains Mitt Romney.',
    'Tiny nipples.',
    'Power.',
    'Oncoming traffic.',
    'A dollop of sour cream.',
    'A slightly shittier parallel universe.',
    'My first kill.',
    'Graphic violence, adult language, and some sexual content.',
    'Fetal alcohol syndrome.',
    'The day the birds attacked.',
    'One Ring to rule them all.',
    'Grandpa\'s ashes.',
    'Basic human decency.',
    'A Burmese tiger pit.',
    'Death by Steven Seagal.',
    'The primal, ball-slapping sex your parents are having right now.',
    'A cat video so cute that your eyes roll back and your spine slides out of your anus.',
    'Cock.',
    'A cop who is also a dog.',
    'Dying alone and in pain.',
    'Gay aliens.',
    'The way white people is.',
    'Reverse cowgirl.',
    'The Quesadilla Explosion Salad™ from Chili\'s®.',
    'Actually getting shot, for real.',
    'Not having sex.',
    'Vietnam flashbacks.',
    'Running naked through a mall, pissing and shitting everywhere.',
    'Nothing.',
    'Warm, velvety muppet sex.',
    'Self-flagellation.',
    'The systematic destruction of an entire people and their way of life.',
    'Samuel L. Jackson.',
    'A boo-boo.',
    'Going around punching people.',
    'The entire Internet.',
    'Some kind of bird-man.',
    'Chugging a lava lamp.',
    'Having sex on top of a pizza.',
    'Indescribable loneliness.',
    'An ass disaster.',
    'Shutting the fuck up.',
    'All my friends dying.',
    'Putting an entire peanut butter and jelly sandwich into the VCR.',
    'Spending lots of money.',
    'Some douche with an acoustic guitar.',
    'Flying robots that kill people.',
    'A greased-up Matthew McConaughey.',
    'An unstoppable wave of fire ants.',
    'Not contributing to society in any meaningful way.',
    'An all-midget production of Shakespeare\'s <i>Richard III</i>.',
    'Screaming like a maniac.',
    'The moist, demanding chasm of his mouth.',
    'Filling every orifice with butterscotch pudding.',
    'Unlimited soup, salad, and breadsticks.',
    'Crying into the pages of Sylvia Plath.',
    'Velcro™.',
    'A PowerPoint presentation.',
    'A surprising amount of hair.',
    'Eating Tom Selleck\'s mustache to gain his powers.',
    'Roland the Farter, flatulist to the king.',
    'That ass.',
    'A pile of squirming bodies.',
    'Buying the right pants to be cool.',
    'Blood farts.',
    'Three months in the hole.',
    'A botched circumcision.',
    'The Land of Chocolate.',
    'Slapping a racist old lady.',
    'A lamprey swimming up the toilet and latching onto your taint.',
    'Jumping out at people.',
    'A black male in his early 20s, last seen wearing a hoodie.',
    'Mufasa\'s death scene.',
    'Bill Clinton, naked on a bearskin rug with a saxophone.',
    'Demonic possession.',
    'The Harlem Globetrotters.',
    'Vomiting mid-blowjob.',
    'My manservant, Claude.',
    'Having shotguns for legs.',
    'Letting everyone down.',
    'A spontaneous conga line.',
    'A vagina that leads to another dimension.',
    'Disco fever.',
    'Getting your dick stuck in a Chinese finger trap with another dick.',
    'Fisting.',
    'The thin veneer of situational causality that underlies porn.',
    'Girls that always be textin\'.',
    'Blowing some dudes in an alley.',
    'Drinking ten 5-hour ENERGYs® to get fifty continuous hours of energy.',
    'Sneezing, farting, and coming at the same time.',
    'Advice from a wise, old black man.',
    'The Devil himself.',
    'The art of seduction.',
    'Funky fresh rhymes.',
    'The light of a billion suns.',
    'Destroying the evidence.',
    'Silence.',
    'Growing a pair.',
    'Synergistic management solutions.',
    'Wet dreams.',
    'A live studio audience.',
    'The Great Depression.',
    'An M16 assault rifle.',
    'Poopy diapers.',
    'Tickling Sean Hannity, even after he tells you to stop.',
    'Stalin.',
    'A spastic nerd.',
    'Rush Limbaugh\'s soft, shitty body.',
    'Capturing Newt Gingrich and forcing him to dance in a monkey suit.',
    'Battlefield amputations.',
    'Brown people.',
    'Rehab.',
    'An ugly face.',
    'Menstrual rage.',
    'An uppercut.',
    'Shiny objects.',
    '50,000 volts straight to the nipples.',
    'A bucket of fish heads.',
    'Hospice care.',
    'Being fat and stupid.',
    'Getting married, having a few kids, buying some stuff, retiring to Florida, and dying.',
    'A pyramid of severed heads.',
    'Crucifixion.',
    'A subscription to Men\'s Fitness.',
    'Some god-damn peace and quiet.',
    'A micropig wearing a tiny raincoat and booties.',
    'Used panties.',
    'The penny whistle solo from "My Heart Will Go On."',
    'A tribe of warrior women.',
    'An oversized lollipop.',
    'Helplessly giggling at the mention of Hutus and Tutsis.',
    'Not wearing pants.',
    'Consensual sex.',
    'Her Majesty, Queen Elizabeth II.',
];

export class PostRefactoring1720656542332 implements MigrationInterface {

    public async up(queryRunner : QueryRunner) : Promise<void> {

        await queryRunner.query('TRUNCATE TABLE card');

        const queryPromiseList = whiteCardTextList.map((text) => {
            return queryRunner.query(
                'INSERT INTO card (text, type) VALUES ($1, $2)',
                [text, 'white'],
            );
        });

        await Promise.all(queryPromiseList);
    }

    public async down(_queryRunner : QueryRunner) : Promise<void> {
    }

}
