import { MigrationInterface, QueryRunner } from 'typeorm';


const blackCardTextList = [
    'Why can\'t I sleep at night?',
    'I got 99 problems but ____ ain\'t one.',
    'What\'s a girl\'s best friend?',
    'What\'s that smell?',
    '____? There\'s an app for that.',
    'This is the way the world ends  This is the way the world ends  Not with a bang but with ____.',
    'What is Batman\'s guilty pleasure?',
    'TSA guidelines now prohibit ____ on airplanes.',
    'What ended my last relationship?',
    'MTV\'s new reality show features eight washed-up celebrities living with ____.',
    'I drink to forget ____.',
    'I\'m sorry, Professor, but I couldn\'t complete my homework because of ____.',
    'During Picasso\'s often-overlooked Brown Period, he produced hundreds of paintings of ____.',
    'Alternative medicine is now embracing the curative powers of ____.',
    'What\'s that sound?',
    'Who stole the cookies from the cookie jar?',
    'What\'s the next Happy Meal® toy?',
    'Anthropologists have recently discovered a primitive tribe that worships ____.',
    'It\'s a pity that kids these days are all getting involved with ____.',
    '____. That\'s how I want to die.',
    'In the new Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time.',
    'What does Dick Cheney prefer?',
    'I wish I hadn\'t lost the instruction manual for ____.',
    'Instead of coal, Santa now gives the bad children ____.',
    'What\'s the most emo?',
    'In 1,000 years, when paper money is but a distant memory, ____ will be our currency.',
    'What\'s the next superhero?',
    'A romantic, candlelit dinner would be incomplete without ____.',
    'Next from J.K. Rowling: Harry Potter and the Chamber of ____.',
    '____. Betcha can\'t have just one!',
    'White people like ____.',
    '____. High five, bro.',
    'During sex, I like to think about ____.',
    'War!<br><br>What is it good for?',
    'BILLY MAYS HERE FOR ____.',
    'What will always get you laid?',
    'When I\'m in prison, I\'ll have ____ smuggled in.',
    'What did I bring back from Mexico?',
    'What are my parents hiding from me?',
    'What helps Obama unwind?',
    'What\'s there a ton of in heaven?',
    'What would grandma find disturbing, yet oddly charming?',
    'What did the U.S. airdrop to the children of Afghanistan?',
    'What\'s the new fad diet?',
    'When I am the President of the United States, I will create the Department of ____.',
    'Major League Baseball has banned ____ for giving players an unfair advantage.',
    'When I am a billionare, I shall erect a 50-foot statue to commemorate ____.',
    'What don\'t you want to find in your Chinese food?',
    'What will I bring back in time to convince people that I am a powerful wizard?',
    'How am I maintaining my relationship status?',
    '____. It\'s a trap!',
    'Coming to Broadway this season, ____: The Musical.',
    'While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ____.',
    'After Hurricane Katrina, Sean Penn brought ____ to all the people of New Orleans.',
    'Due to a PR fiasco, Walmart no longer offers ____.',
    'What never fails to liven up the party?',
    'But before I kill you, Mr. Bond, I must show you ____.',
    'What gives me uncontrollable gas?',
    'What\'s my secret power?',
    'When Pharaoh remained unmoved, Moses called down a plague of ____.',
    'The class field trip was completely ruined by ____.',
    'What do old people smell like?',
    'What am I giving up for Lent?',
    'In Michael Jackson\'s final moments, he thought about ____.',
    'In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ____.',
    'Why do I hurt all over?',
    'Studies show that lab rats navigate mazes 50% faster after being exposed to ____.',
    'I do not know with which weapons World War III will be fought, but World War IV will be fought with ____.',
    'Life was difficult for cavemen before ____.',
    'What\'s Teach for America using to inspire inner city students to succeed?',
    'What\'s the crustiest?',
    '____: Good to the last drop.',
    'What did Vin Diesel eat for dinner?',
    '____: kid-tested, mother-approved.',
    'What gets better with age?',
    'Why am I sticky?',
    'What\'s my anti-drug?',
    'And the Academy Award for ____ goes to ____.',
    'For my next trick, I will pull ____ out of ____.',
    '____ is a slippery slope that leads to ____.',
    'In M. Night Shyamalan\'s new movie, Bruce Willis discovers that ____ had really been ____ all along.',
    'In a world ravaged by ____, our only solace is ____.',
    'In his new summer comedy, Rob Schneider is ____ trapped in the body of ____.',
    'Rumor has it that Vladimir Putin\'s favorite delicacy is ____ stuffed with ____.',
    'I never truly understood ____ until I encountered ____.',
    'Make a haiku.',
    'Lifetime® presents ____, the story of ____.',
    'When I was tripping on acid, ____ turned into ____.',
    'That\'s right, I killed ____. How, you ask? ____.',
    '____ + ____ = ____.',
    'Maybe she\'s born with it. Maybe it\'s ____.',
    'Dear Abby,<br><br>I\'m having some trouble with ____ and would like your advice.',
    'What\'s the next superhero/sidekick duo?',
    'In L.A. County Jail, word is you can trade 200 cigarettes for ____.',
    'After the earthquake, Sean Penn brought ____ to the people of Haiti.',
    'Next on ESPN2, the World Series of ____.',
    'Step 1: ____. Step 2: ____. Step 3: Profit.',
    'Life for American Indians was forever changed when the White Man introduced them to ____.',
    'test',
    'Starting Canadian Black Cards',
    'End Canadian Black Cards',
    'end bonus misprint bonus card',
    'begin First Expansion',
    'He who controls ____ controls the world.',
    'The CIA now interrogates enemy agents by repeatedly subjecting them to ____.',
    'Dear Sir or Madam, We regret to inform you that the Office of ____ has denied your request for ____.',
    'In Rome, there are whisperings that the Vatican has a secret room devoted to ____.',
    'Science will never explain the origin of ____.',
    'When all else fails, I can always masturbate to ____.',
    'I learned the hard way that you can\'t cheer up a grieving friend with ____.',
    'In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated ____.',
    'An international tribunal has found ____ guilty of ____.',
    'The socialist governments of Scandinavia have declared that access to ____ is a basic human right.',
    'In his new self-produced album, Kanye West raps over the sounds of ____.',
    'What\'s the gift that keeps on giving?',
    'This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only ____ and his wits.',
    'When I pooped, what came out of my butt?',
    'In the distant future, historians will agree that ____ marked the beginning of America\'s decline.',
    'In a pinch, ____ can be a suitable substitute for ____.',
    'What has been making life difficult at the nudist colony?',
    'Michael Bay\'s new three-hour action epic pits ____ against ____.',
    'And I would have gotten away with it, too, if it hadn\'t been for ____!',
    'What brought the orgy to a grinding halt?',
    'end first expansion',
    'During his midlife crisis, my dad got really into ____.',
    '____ would be woefully incomplete without ____.',
    'My new favorite porn star is Joey "____" McGee.',
    'Before I run for president, I must destroy all evidence of my involvement with ____.',
    'This is your captain speaking. Fasten your seatbelts and prepare for ____.',
    'In his newest and most difficult stunt, David Blaine must escape from ____.',
    'The Five Stages of Grief: denial, anger, bargaining, ____, acceptance.',
    'My mom freaked out when she looked at my browser history and found ____.com/____.',
    'I went from ____ to ____, all thanks to ____.',
    'Members of New York\'s social elite are paying thousands of dollars just to experience ____.',
    'This month\'s Cosmo: "Spice up your sex life by bringing ____ into the bedroom."',
    'Little Miss Muffet Sat on a tuffet, Eating her curds and ____.',
    'If God didn\'t want us to enjoy ____, he wouldn\'t have given us ____.',
    'My country, \'tis of thee, sweet land of ____.',
    'After months of debate, the Occupy Wall Street General Assembly could only agree on "More ____!"',
    'I spent my whole life working toward ____, only to have it ruined by ____.',
    'Next time on Dr. Phil: How to talk to your child about ____.',
    'Only two things in life are certain: death and ____.',
    'Everyone down on the ground! We don\'t want to hurt anyone. We\'re just here for ____.',
    'The healing process began when I joined a support group for victims of ____.',
    'The votes are in, and the new high school mascot is ____.',
    'Charades was ruined for me forever when my mom had to act out ____.',
    'Before ____, all we had was ____.',
    'Tonight on 20/20: What you don\'t know about ____ could kill you.',
    'You haven\'t truly lived until you\'ve experienced ____ and ____ at the same time.',
    '____: Hours of fun. Easy to use. Perfect for ____!',
    'Turns out that ____-Man was neither the hero we needed nor wanted.',
    'What left this stain on my couch?',
    'Call the law offices of Goldstein & Goldstein, because no one should have to tolerate ____ in the workplace.',
    'A successful job interview begins with a firm handshake and ends with ____.',
    'Lovin\' you is easy \'cause you\'re ____.',
    'Money can\'t buy me love, but it can buy me ____.',
    'Listen, son. If you want to get involved with ____, I won\'t stop you. Just steer clear of ____.',
    'During high school, I never really fit in until I found ____ club.',
    'Hey baby, come back to my place and I\'ll show you ____.',
    'My life is ruled by a vicious cycle of ____ and ____.',
    'To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of ____.',
    'Finally! A service that delivers ____ right to your door.',
    'My gym teacher got fired for adding ____ to the obstacle course.',
    'When you get right down to it, ____ is just ____.',
    'As part of his daily regimen, Anderson Cooper sets aside 15 minutes for ____.',
    'In the seventh circle of Hell, sinners must endure ____ for all eternity.',
    'After months of practice with ____, I think I\'m finally ready for ____.',
    'The blind date was going horribly until we discovered our shared interest in ____.',
    '____. Awesome in theory, kind of a mess in practice.',
    'With enough time and pressure, ____ will turn into ____.',
    'I\'m not like the rest of you. I\'m too rich and busy for ____.',
    'And what did <i>you</i> bring for show and tell?',
    'Having problems with ____? Try ____!',
    'As part of his contract, Prince won\'t perform without ____ in his dressing room.',
    'How did I lose my virginity?',
    'Here is the church<br>Here is the steeple<br>Open the doors<br>And there is ____.',
    'During his childhood, Salvador Dalí produced hundreds of paintings of ____.',
    'In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?',
    'What don\'t you want to find in your Kung Pao chicken?',
    'The Smithsonian Museum of Natural History has just opened an exhibit on ____.',
];

export class PostRefactoring1720656454283 implements MigrationInterface {

    public async up(queryRunner : QueryRunner) : Promise<void> {

        await queryRunner.query('TRUNCATE TABLE card');

        const queryPromiseList = blackCardTextList.map((text) => {
            return queryRunner.query(
                'INSERT INTO card (text, type) VALUES ($1, $2)',
                [text, 'black'],
            );
        });

        await Promise.all(queryPromiseList);
    }

    public async down(_queryRunner : QueryRunner) : Promise<void> {
    }

}
