name: CrudeCards - Pipeline - Dev - Web
on:
    push:
        branches: [dev]
    workflow_dispatch:

jobs:
    deploy-cloud-run:
        runs-on: ubuntu-latest
        environment: Development
        env:
            EXAMPLE_WF_ENV: "Hello Im an example workflow env"

        # trunk-ignore(checkov/CKV2_GHA_1)
        permissions:
            contents: write # Allows the job to write back to the repository, necessary for actions like pushing commits or tags
            id-token: write

        steps:
            # Get last updates
            - name: Checkout
              uses: actions/checkout@v4

            # Install pnpm
            - name: Install pnpm
              run: npm install -g pnpm

            # Set up   Node.js 20
            - name: Setup Node.js v20
              uses: actions/setup-node@v3
              with:
                  node-version-file: .nvmrc
                  check-latest: true
                  node-version: "20"
                  cache: pnpm

            # Write to complete env file
            - name: env file
              run: |-
                  echo NEXT_PUBLIC_BROWSER_WINDOW_LOCATION_ORIGIN        = "${{ vars.NEXT_PUBLIC_BROWSER_WINDOW_LOCATION_ORIGIN       }}" >> .env
                  echo NEXT_PUBLIC_GOOGLE_ANALYTICS_ID                   = "${{ vars.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID                  }}" >> .env
                  echo NEXT_PUBLIC_APP_ID                                = "${{ vars.NEXT_PUBLIC_APP_ID                               }}" >> .env
                  echo NEXT_PUBLIC_NEXT_COUNTDOWN_TIMER_DURATION_SECONDS = "${{ vars.NEXT_PUBLIC_NEXT_COUNTDOWN_TIMER_DURATION_SECONDS}}" >> .env
                  echo NEXT_GOOGLE_GEMINI_API_KEY                        = "${{ vars.NEXT_GOOGLE_GEMINI_API_KEY                       }}" >> .env
                  echo NEXT_PUBLIC_IS_DEBUG_OVERLAY_VISIBLE              = "${{ vars.NEXT_PUBLIC_IS_DEBUG_OVERLAY_VISIBLE             }}" >> .env
                  echo NEXT_PUBLIC_WEB_SOCKET_HOST_ORIGIN                = "${{ vars.NEXT_PUBLIC_WEB_SOCKET_HOST_ORIGIN               }}" >> .env

            - run: node -v
            - run: pwd
            - run: pnpm install
            - run: pnpm --prefix src/api install

            # Disable next.js spyware
            - run: pnpm run job:disable-snooping

            # Increment the version number of package.json
            - run: pnpm run ci-semantic-release
